// <auto-generated />
using Digitala_FiskGuiden.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Digitala_FiskGuiden.Migrations
{
    [DbContext(typeof(FiskContext))]
    [Migration("20210122095657_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("Digitala_FiskGuiden.Models.Fisk", b =>
                {
                    b.Property<int>("FiskId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Art")
                        .HasColumnType("TEXT");

                    b.Property<string>("Fakta")
                        .HasColumnType("TEXT");

                    b.HasKey("FiskId");

                    b.ToTable("Fiskar");
                });

            modelBuilder.Entity("Digitala_FiskGuiden.Models.Klass", b =>
                {
                    b.Property<int>("KlassId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FiskKlass")
                        .HasColumnType("TEXT");

                    b.HasKey("KlassId");

                    b.ToTable("Klasser");
                });
#pragma warning restore 612, 618
        }
    }
}
