// <auto-generated />
using Digitala_FiskGuiden.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Digitala_FiskGuiden.Migrations
{
    [DbContext(typeof(FiskContext))]
    partial class FiskContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("Digitala_FiskGuiden.Models.Fisk", b =>
                {
                    b.Property<int>("FiskId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Art")
                        .HasColumnType("TEXT");

                    b.Property<string>("Fakta")
                        .HasColumnType("TEXT");

                    b.Property<int>("KlassId")
                        .HasColumnType("INTEGER");

                    b.HasKey("FiskId");

                    b.HasIndex("KlassId");

                    b.ToTable("Fiskar");
                });

            modelBuilder.Entity("Digitala_FiskGuiden.Models.Klass", b =>
                {
                    b.Property<int>("KlassId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FiskKlass")
                        .HasColumnType("TEXT");

                    b.HasKey("KlassId");

                    b.ToTable("Klasser");
                });

            modelBuilder.Entity("Digitala_FiskGuiden.Models.Fisk", b =>
                {
                    b.HasOne("Digitala_FiskGuiden.Models.Klass", "Klass")
                        .WithMany("Fiskar")
                        .HasForeignKey("KlassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Klass");
                });

            modelBuilder.Entity("Digitala_FiskGuiden.Models.Klass", b =>
                {
                    b.Navigation("Fiskar");
                });
#pragma warning restore 612, 618
        }
    }
}
